if (self.CavalryLogger) { CavalryLogger.start_js(["0QhOCko"]); }

__d("LWICometEditingRootContentQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"4113999131955144",metadata:{},name:"LWICometEditingRootContentQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("LWICometManagementRootContentQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"6254529624573253",metadata:{},name:"LWICometManagementRootContentQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("PagesCometAdminWhatsappUpsellDialogQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3816369131824150",metadata:{},name:"PagesCometAdminWhatsappUpsellDialogQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("AdsLWICoBEditingDialog.entrypoint",["JSResourceForInteraction","LWICometEditingRootContentQuery$Parameters","WebPixelRatio"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){return{queries:{editingRootQueryRef:{parameters:b("LWICometEditingRootContentQuery$Parameters"),variables:{boostID:a.boostID,scale:d("WebPixelRatio").get(),shouldFetchBrandedTemplate:!1}}}}},root:c("JSResourceForInteraction")("AdsLWICoBEditingDialog.react").__setRef("AdsLWICoBEditingDialog.entrypoint")};g["default"]=a}),98);
__d("AdsLWICoBManagementDialog.entrypoint",["JSResourceForInteraction","LWICometManagementRootContentQuery$Parameters","WebPixelRatio"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){return{queries:{managementRootQueryRef:{parameters:b("LWICometManagementRootContentQuery$Parameters"),variables:{boostID:a.boostID,scale:d("WebPixelRatio").get()}}}}},root:c("JSResourceForInteraction")("AdsLWICoBManagementDialog.react").__setRef("AdsLWICoBManagementDialog.entrypoint")};g["default"]=a}),98);
__d("LWICometManagementRoot.entrypoint",["JSResourceForInteraction","LWICometManagementRootContentQuery$Parameters","WebPixelRatio"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){a=String(a.routeParams.boost_id);return{queries:{managementRootQueryReference:{parameters:b("LWICometManagementRootContentQuery$Parameters"),variables:{boostID:a,scale:d("WebPixelRatio").get()}}}}},root:c("JSResourceForInteraction")("LWICometManagementRoot.react").__setRef("LWICometManagementRoot.entrypoint")};g["default"]=a}),98);
__d("LWIAdCenterLoggerContext",["react"],(function(a,b,c,d,e,f,g){"use strict";a=d("react");b=a.createContext({mapping:null});g["default"]=b}),98);
__d("PagesCometAdminLiveTabContext",["react"],(function(a,b,c,d,e,f,g){"use strict";a=d("react");b={isLeftNavNuxVisible:!1,pageID:"",setIsLeftNavNuxVisible:function(){}};c=a.createContext(b);g["default"]=c}),98);
__d("PagesCometAdminWhatsappUpsellDialog.entrypoint",["JSResourceForInteraction","PagesCometAdminWhatsappUpsellDialogQuery$Parameters"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){return{queries:{dialogQueryReference:{parameters:c("PagesCometAdminWhatsappUpsellDialogQuery$Parameters"),variables:{pageID:a.pageID}}}}},root:c("JSResourceForInteraction")("PagesCometAdminWhatsappUpsellDialog.react").__setRef("PagesCometAdminWhatsappUpsellDialog.entrypoint")};g["default"]=a}),98);